# These are supported funding model platforms

github: yash130021-beep # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# buymeacoffee: # Replace with a single Buy Me a Coffee username
# custom: ['https://example.com'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
